class producto{
    constructor(nombre, horario, sala, genero, imagen, descripcion, unidad,precioProducto, tipoDeProducto,totalParcial){
        this.nombre=nombre;
        this.horario= horario;
        this.sala= sala;
        this.genero=genero;
        this.imagen=imagen;
        this.descripcion=descripcion;
        this.unidad=unidad;
        this.precioProducto= precioProducto;
        this.tipoDeProducto=tipoDeProducto;
        this.totalParcial=totalParcial;
        this.id= (productos.length+1);
    }
}

class funcion {
    constructor(nombre,precio){
        this.nombre= nombre;
        this.precio=parseInt(precio);
    }
}

const funciones=[];
funciones.push(new funcion("2D",600));
funciones.push(new funcion("3D",800));
funciones.push(new funcion("4D",1000));

const productos =[];
// Generacion productos--> peliculas.
productos.push(new producto("BATMAN","19.15hs","Sala N° 1.","ACCION", "./assets/images/batman.jpg","Luchando contra el crimen, Batman explora la corrupción existente en la ciudad de Gotham y el vínculo de esta con su propia familia. Además, entrará en conflicto con un asesino en serie conocido como 'el Acertijo'.",1,funciones[0].precio,funciones[0].nombre,0));
productos.push(new producto("BATMAN 3D","19.15hs","Sala N° 1.","ACCION", "./assets/images/batman3.png","Luchando contra el crimen, Batman explora la corrupción existente en la ciudad de Gotham y el vínculo de esta con su propia familia. Además, entrará en conflicto con un asesino en serie conocido como 'el Acertijo'.",1,funciones[1].precio,funciones[1].nombre,0));
productos.push(new producto("RAPIDO Y FURIOSO","20:00hs","Sala N° 2.","ACCION", "./assets/images/rapido.jpg","En la cuidad de Los Ángeles, el corredor de autos y ex convicto Dominic Toretto se vuelve sospechoso ante la policía de ser el responsable de una serie de robos a trailer llenos de costosos artefactos electrónicos, que se llevan a cabo de noche en la carretera.",1,funciones[0].precio,funciones[0].nombre,0));
productos.push(new producto("RAPIDO Y FURIOSO 4D","16:00hs","Sala N° 12.","ACCION", "./assets/images/rapido4d.png","En la cuidad de Los Ángeles, el corredor de autos y ex convicto Dominic Toretto se vuelve sospechoso ante la policía de ser el responsable de una serie de robos a trailer llenos de costosos artefactos electrónicos, que se llevan a cabo de noche en la carretera.",1,funciones[2].precio,funciones[2].nombre,0));
productos.push(new producto("TITANIC","12:00hs","Sala N° 4","DRAMA","./assets/images/titanic.jpg","La trama, una epopeya romántica,​​ relata la relación de Jack Dawson y Rose DeWitt Bukater, dos jóvenes que se conocen y se enamoran a bordo del transatlántico RMS Titanic en su viaje inaugural desde Southampton (Inglaterra) a Nueva York (Estados Unidos) en abril de 1912.",1,funciones[0].precio,funciones[0].nombre,0)); 
productos.push(new producto("TITANIC 3D","12:00hs","Sala N° 4","DRAMA","./assets/images/titanic3.png","La trama, una epopeya romántica,​​ relata la relación de Jack Dawson y Rose DeWitt Bukater, dos jóvenes que se conocen y se enamoran a bordo del transatlántico RMS Titanic en su viaje inaugural desde Southampton (Inglaterra) a Nueva York (Estados Unidos) en abril de 1912.",1,funciones[1].precio,funciones[1].nombre,0)); 
productos.push(new producto("DRAGON BALL Z","18:00hs","Sala N° 2.","ACCION","./assets/images/dragon.jpg","Su trama describe las aventuras de Gokū, un guerrero saiyajin, cuyo fin es proteger a la Tierra de otros seres que quieren conquistarla y exterminar a la humanidad.",1,funciones[0].precio,funciones[0].nombre,0));
productos.push(new producto("HARRY POTTER","10:00hs","Sala N° 3.","ACCION", "./assets/images/harry.jpg","Cuando Harry Potter cumple 11 años se entera que es huérfano, hijo de dos magos y que posee poderes mágicos. En la Escuela de Magia y Brujería de Hogwarts aprende a jugar el deporte de alturas, Quidditch y juega un emocionante juego de ajedrez, en vías a encarar al Mago Oscuro que está empeñado en destruirlo.",1,funciones[0].precio,funciones[0].nombre,0));
productos.push(new producto("LA PANTERA ROSA","10:00hs","Sala N° 7.","COMEDIA", "./assets/images/pantera.jpg","En La Pantera Rosa, una comedia llena de acción, el torpe Inspector Clouseau (Steve Martin) se enfrenta al caso más importante de su carrera. El famoso entrenador de fútbol, Yves Gluant, acaba de llevar al equipo de Francia a la victoria frente a la selección de China.",1,funciones[0].precio,funciones[0].nombre,0)); 
productos.push(new producto("LA PANTERA ROSA 3D","10:00hs","Sala N° 7.","COMEDIA", "./assets/images/pantera3.png","En La Pantera Rosa, una comedia llena de acción, el torpe Inspector Clouseau (Steve Martin) se enfrenta al caso más importante de su carrera. El famoso entrenador de fútbol, Yves Gluant, acaba de llevar al equipo de Francia a la victoria frente a la selección de China.",1,funciones[1].precio,funciones[1].nombre,0)); 
productos.push(new producto("ROBOCOT","22:00hs","Sala N° 5.","ACCION","./assets/images/robocot.jpg","RoboCop se centra en un oficial de policía que fue brutalmente asesinado y posteriormente recreado como un cyborg sobrehumano conocido como 'RoboCop'.",1,funciones[0].precio,funciones[0].nombre,0));
productos.push(new producto("ROBOCOT 4D","22:00hs","Sala N° 6.","ACCION","./assets/images/robocop4d.png","RoboCop se centra en un oficial de policía que fue brutalmente asesinado y posteriormente recreado como un cyborg sobrehumano conocido como 'RoboCop'.",1,funciones[2].precio,funciones[2].nombre,0));
productos.push(new producto("QUE PASO AYER","18:00hs","Sala N° 8.","COMEDIA", "./assets/images/quePaso.jpg","Una despedida de soltero en Las Vegas se sale de control cuando el novio desaparece y sus tres amigos despiertan sin recordar el desenfreno de la noche anterior. Ve todo lo que quieras. Esta comedia ganó Globo de Oro a la mejor película y fue una de las más taquilleras de 2009.",1,funciones[0].precio,funciones[0].nombre,0));
productos.push(new producto("QUE PASO AYER 3D","18:00hs","Sala N° 8.","COMEDIA", "./assets/images/paso3.png","Una despedida de soltero en Las Vegas se sale de control cuando el novio desaparece y sus tres amigos despiertan sin recordar el desenfreno de la noche anterior. Ve todo lo que quieras. Esta comedia ganó Globo de Oro a la mejor película y fue una de las más taquilleras de 2009.",1,funciones[1].precio,funciones[1].nombre,0));
productos.push(new producto("LA VIDA ES BELLA","15:00hs","Sala N° 6.","DRAMA" ,"./assets/images/vida.jpg","Guido (Roberto Benigni) sueña con tener su propia librería. Por eso, viaja a la ciudad de Arezzo, en la Toscana italiana y donde vive su tío, para instalarse allí. Guido conoce a la maestra de escuela Dora (Nicoletta Braschi) y se enamora perdidamente de ella.",1,funciones[0].precio,funciones[0].nombre,0));
productos.push(new producto("SCARY MOVIE","11:00hs","Sala N° 7.","COMEDIA" ,"./assets/images/scary.jpg","Un grupo de desorientados adolescentes descubren que existe un asesino entre ellos. La heroína Cyndi Campbell y su grupo de despistados amigos se verán aterrorizados por un singular psicópata enmascarado que pretende vengarse de ellos después de que lo atropellaran por accidente el pasado Halloween.",1,funciones[0].precio,funciones[0].nombre,0));
productos.push(new producto("SCARY MOVIE 4D","17:30hs","Sala N° 9.","COMEDIA" ,"./assets/images/scary4d.png","Un grupo de desorientados adolescentes descubren que existe un asesino entre ellos. La heroína Cyndi Campbell y su grupo de despistados amigos se verán aterrorizados por un singular psicópata enmascarado que pretende vengarse de ellos después de que lo atropellaran por accidente el pasado Halloween.",1,funciones[2].precio,funciones[2].nombre,0));
productos.push(new producto("TONTO Y RE TONTO","16:00hs","Sala N° 8.","COMEDIA", "./assets/images/tonto.jpg","Lloyd Christmas (Jim Carrey) es un ingenuo conductor de limusinas residente de Providence, Rhode Island, que se encapricha con su acompañante, Mary Swanson (Lauren Holly), cuando él la lleva al aeropuerto. Mary se dirigía a casa de su familia en Aspen, Colorado, pero deja un maletín en el aeropuerto.",1,funciones[0].precio,funciones[0].nombre,0));
productos.push(new producto("TED","22:00hs","Sala N° 10.","COMEDIA", "./assets/images/ted.jpg","En 1985, John Bennett, de ocho años, es un hijo único sin amigos que vive en Norwood, Massachusetts, un suburbio de Boston, que deseaba su nuevo regalo de Navidad, un osito de peluche llamado Ted, para volver a la vida y convertirse en su mejor amigo.",1,funciones[0].precio,funciones[0].nombre,0));
productos.push(new producto("ZOOLANDER","23:00hs","Sala N° 9.","COMEDIA","./assets/images/zoolander.jpg","Derek Zoolander (Ben Stiller) ha sido el modelo masculino más cotizado durante los últimos tres años. La noche de la gala que podría suponer su cuarta corona, el galardón se lo lleva un nuevo modelo llamado Hansel (Owen Wilson). Derek queda en entredicho y como un idiota, y decide retirarse.",1,funciones[0].precio,funciones[0].nombre,0));
productos.push(new producto("JURASSIC PARK","21:00hs","Sala N° 1.","ACCION","./assets/images/jurassic.jpg","John Hammond, magnate propietario de la empresa multinacional en bioingeniería InGen, ha soñado toda su vida con construir el mayor parque de atracciones del mundo. Una isla en Costa Rica donde habiten las criaturas más espectaculares que han pisado la Tierra: los dinosaurios. Pese a la extinción de estos reptiles, InGen ha logrado clonar diversas especies mediante la manipulación de segmentos de ADN de la propia sangre de dinosaurio, encontrada en mosquitos fosilizados en ámbar.",1,funciones[0].precio,funciones[0].nombre,0));
productos.push(new producto("JURASSIC PARK 3D","20:15hs","Sala N° 3.","ACCION","./assets/images/jurassic3.png","John Hammond, magnate propietario de la empresa multinacional en bioingeniería InGen, ha soñado toda su vida con construir el mayor parque de atracciones del mundo. Una isla en Costa Rica donde habiten las criaturas más espectaculares que han pisado la Tierra: los dinosaurios. Pese a la extinción de estos reptiles, InGen ha logrado clonar diversas especies mediante la manipulación de segmentos de ADN de la propia sangre de dinosaurio, encontrada en mosquitos fosilizados en ámbar.",1,funciones[1].precio,funciones[1].nombre,0));
productos.push(new producto("JURASSIC PARK 4D","21:00hs","Sala N° 5.","ACCION","./assets/images/jurassic4d.png","John Hammond, magnate propietario de la empresa multinacional en bioingeniería InGen, ha soñado toda su vida con construir el mayor parque de atracciones del mundo. Una isla en Costa Rica donde habiten las criaturas más espectaculares que han pisado la Tierra: los dinosaurios. Pese a la extinción de estos reptiles, InGen ha logrado clonar diversas especies mediante la manipulación de segmentos de ADN de la propia sangre de dinosaurio, encontrada en mosquitos fosilizados en ámbar.",1,funciones[2].precio,funciones[2].nombre,0));
productos.push(new producto("FORREST GUMP","21:00hs","Sala N° 8.","DRAMA", "./assets/images/forrest.jpg","Basada en la novela homónima del escritor Winston Groom, la película fue dirigida por Robert Zemeckis y protagonizada por Tom Hanks, Robin Wright, Gary Sinise y Sally Field. La historia describe varias décadas de la vida de Forrest Gump",1,funciones[0].precio,funciones[0].nombre,0)); 
productos.push(new producto("EL CLUB DE LA PELEA","23:15hs","Sala N° 5.","DRAMA", "./assets/images/club4d.png","Viajando en avión conoce a Tyler Durden (Brad Pitt), un vendedor de jabón con una clara ideología: el perfeccionismo es para los débiles y la destrucción de uno mismo es lo que, verdaderamente, vale la pena en la vida. A Jack le convence ese argumento y decide unirse a Tyler para pelear.",1,funciones[2].precio,funciones[2].nombre,0)); 
// --> PRODUCTOS TIENDA
productos.push(new producto("BEBIDA 500ML A ELECCION","","","TIENDA","./assets/images/gaseosea.png","GASEOSA 500ML A ELECCION: podrás elegir entre cualquiera de nuestros productos (gaseoesa, agua con y sin gas o jugos).",1,350,"Unid.",0));
productos.push(new producto("BALDE POCHOCLOS CHICO","","","TIENDA","./assets/images/pochocloChico.png","BALDE POCHOCLOS CHICO: dulce o salados para poder disfrutar de su función.",1,450,"Unid.",0));
productos.push(new producto("BALDE POCHOCLOS GRANDE","","","TIENDA","./assets/images/balde.png","BALDE POCHOCLOS GRANDE: a diferencia del balde chico, este no solo es más grande sino también viene con el diseño de tu película elegida",1,1000,"Unid.",0));
productos.push(new producto("COMBO BURGUER PAPAS BEBIDA","","","TIENDA","./assets/images/comboHamburguesa.png","COMBO BURGUER PAPAS BEBIDA: podrás personalizar tu hamburguesa con distintos y variados ingredientes y salsas. Incluye bebida a elección y papas fritas deliciosas.",1,2500,"Unid.",0));
productos.push(new producto("POCHOCLO CHICO + 2 BEBIDAS","","","TIENDA","./assets/images/gaseaosa2chico.png","BALDE POCHOCLOS CHICO: dulce o salados para poder disfrutar de su función. + 2 GASEOSAS 500ML A ELECCION: podrás elegir entre cualquiera de nuestros productos (gaseoesa, agua con y sin gas o jugos).",1,1100,"Unid.",0));
productos.push(new producto("BALDE GRANDE + DOS BEBIDAS","","","TIENDA","./assets/images/gaseosa2Grande.png","BALDE POCHOCLOS GRANDE: a diferencia del balde chico, este no solo es más grande sino también viene con el diseño de tu película elegida + 2 GASEOSAS 500ML A ELECCION: podés elegir entre cualquiera de nuestros productos (gaseoesa, agua con y sin gas o jugos).",1,1300,"Unid.",0));
productos.push(new producto("PAPAS FRITAS MEDIANAS","","","TIENDA","./assets/images/papas.png","PAPAS FRITAS: todo el sabor de unas deliciosas papas fritas para acompañar tu función",1,350,"Unid.",0));
productos.push(new producto("HAMBURGUESA COMPLETA","","","TIENDA","./assets/images/hamburguesa.png","HAMBURGUESA COMPLETA: podrás personalizar tu hamburguesa con distintos y variados ingredientes y salsas.",1,850,"Unid.",0));
productos.push(new producto("PANCHO + BEBIDA A ELECCION","","","TIENDA","./assets/images/panchoGaseosa.png","PANCHO: super pancho que podrás personalizar con distintas salsas a elección + GASEOSA 500ML A ELECCION: podrás elegir entre cualquiera de nuestros productos (gaseoesa, agua con y sin gas o jugos).",1,950,"Unid.",0));
productos.push(new producto("POCHOCLO CHICO + BEBIDA","","","TIENDA","./assets/images/chicoGaseosa.png","BALDE POCHOCLOS CHICO: dulce o salados para poder disfrutar de su función. + GASEOSA 500ML A ELECCION: podrás elegir entre cualquiera de nuestros productos (gaseoesa, agua con y sin gas o jugos).",1,650,"Unid.",0));
